### ISSUE TITLE
Bug, 为什么按D不能右转？

### ISSUE THREAD

**Issue by Konfido** [heyzxz/all-about-pcol#3]
为什么按D不能右转？难道跟chrome插件冲突？

**Comment by heyzxz** [comment]
与插件冲突是很可能的，先试试看关掉插件行不行，如果还不行请说下系统版本以及浏览器版本。谢谢

**Comment by Konfido** [comment]
确实跟插件冲突，Vimium，添加规则，禁用d键，现在可以玩了～
